version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - php
      - mariadb
    command: bash -c "composer install && nginx -g 'daemon off;'"
    environment:
      COMPOSER_HOME: /composer
    volumes:
      - ./web:/var/www/html
      - ./composer:/composer
    working_dir: /var/www/html

  php:
    image: php:8.1-fpm
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes:
      - ./data:/var/lib/mysql